version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  iis:
    build: .
    container_name: iis
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ../frontend
    container_name: react_app
    command: npm start
    volumes:
      - ../frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    depends_on:
      - iis
    networks:
      - app-network

volumes:
  postgres_data: