# Generated by Django 5.1.3 on 2024-11-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_proposedcategory_id'),
        ('shop', '0004_alter_order_id'),
    ]

    operations = [
    ]
