# Generated by Django 5.1.3 on 2024-11-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_is_approved_product_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proposedproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
